---
title: "Analysis of Wine Data"
author: "Andrew Prozorovsky"
date: "`r sys.Date()`"
output: "html_document"
---

```{r}
# install.packages("hms")
# install.packages("rmarkdown")
# install.packages("readr")
# install.packages("ggplot2")
```

```{r message=FALSE, warning=FALSE}
# load packages
library(readr)
library(dplyr)
library(ggplot2)
library(ggrepel)
```

```{r message=FALSE, warning=FALSE}
# load visits and checkouts data
wine_reviews <- read_csv('Resources/winemag-data-130k-v2.csv')
```

```{r}
# inspect dataframe and fix column name
head(wine_reviews)
print(nrow(wine_reviews))
print(length(wine_reviews))
wine_reviews = wine_reviews %>%
    rename("id" = "...1")
col_names = colnames(wine_reviews)
print(col_names)
```

```{r}
wine_counts = wine_reviews %>%
  group_by(country) %>%
  summarise(wine_count = n()) %>%
  arrange(desc(wine_count))

top_10_countries = head(wine_counts, 10)
```

```{r}
# bar chart that groups and counts the data by country of origin
countries_bar = ggplot(wine_counts, aes(x = reorder(country, -wine_count), y = wine_count)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = wine_count), vjust = -0.5, size = 3) +
  ggtitle("Number of Wines by Country") +
  xlab("Country") +
  ylab("Number of Wines") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

ggsave("Visualizations/num_wines_by_country.png", countries_bar, width = 8, height = 6, units = "in", dpi = 300)

countries_bar
```

```{r}
# group, order, and filter the data so only the top 15 countries are shown on the chart
top_10_countries_bar = ggplot(top_10_countries, aes(x = reorder(country, -wine_count), y = wine_count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = wine_count), vjust = -0.5, size = 3) +
  ggtitle("Top 10 Countries by Number of Wines") +
  xlab("Country") +
  ylab("Number of Wines") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave("Visualizations/num_wines_by_country_top10.png", top_10_countries_bar, width = 8, height = 6, units = "in", dpi = 300)

top_10_countries_bar
```

```{r}
# scatterplot of price of wines against points
price_points_plot = ggplot(wine_reviews, aes(x = points, y = price)) +
  geom_point(alpha=0.4, aes(color="darkviolet")) +
  labs(title = "Scatterplot of Points vs. Price",
       x = "Points",
       y = "Price") +
  geom_smooth()

ggsave("Visualizations/points_vs_price_scatter.png", price_points_plot, width = 8, height = 6, units = "in", dpi = 300)

price_points_plot
```

```{r}
# graph of top wineries
winery_counts = wine_reviews %>%
  group_by(winery) %>%
  summarise(winery_count = n()) %>%
  arrange(desc(winery_count))

top_10_wineries = head(winery_counts, 10)

top_10_wineries_bar = ggplot(top_10_wineries, aes(x = reorder(winery, -winery_count), y = winery_count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = winery_count), vjust = -0.5, size = 3) +
  ggtitle("Top 10 Wineries by Number of Wines") +
  xlab("Winery") +
  ylab("Number of Wines") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave("Visualizations/num_wines_by_winery_top10.png", top_10_wineries_bar, width = 8, height = 6, units = "in", dpi = 300)

top_10_wineries_bar
```

```{r}
# graph of top varieties
variety_counts = wine_reviews %>%
  group_by(variety) %>%
  summarise(variety_count = n()) %>%
  arrange(desc(variety_count))

top_10_varieties = head(variety_counts, 10)

top_10_varieties_bar = ggplot(top_10_varieties, aes(x = reorder(variety, -variety_count), y = variety_count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = variety_count), vjust = -0.5, size = 3) +
  ggtitle("Top 10 Wine Varieties from the Data") +
  xlab("Variety") +
  ylab("Number of Wines") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave("Visualizations/num_wines_by_variety_top10.png", top_10_varieties_bar, width = 8, height = 6, units = "in", dpi = 300)

top_10_varieties_bar
```


```{r}
# graph of top provinces
province_counts = wine_reviews %>%
  group_by(province) %>%
  summarise(province_count = n()) %>%
  arrange(desc(province_count))

top_10_provinces = head(province_counts, 10)

top_10_provinces_bar = ggplot(top_10_provinces, aes(x = reorder(province, -province_count), y = province_count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = province_count), vjust = -0.5, size = 3) +
  ggtitle("Top 10 Provinces by Number of Wines") +
  xlab("Province") +
  ylab("Number of Wines") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave("Visualizations/num_wines_by_province_top10.png", top_10_provinces_bar, width = 8, height = 6, units = "in", dpi = 300)

top_10_provinces_bar
```

```{r}
# scatterplot of wineries by average points
winery_counts = wine_reviews %>%
  group_by(winery) %>%
  summarise(observations = n())

top_50_wineries = winery_counts %>%
  top_n(50, wt = observations) %>%
  pull(winery)

top_50_wineries = wine_reviews %>%
  filter(winery %in% top_50_wineries)

top_50_wineries_points_graph = ggplot(top_50_wineries, aes(x = winery, y = points, color = country)) +
  stat_summary(fun = "mean", geom = "point", size = 3) +
  labs(title = "Scatterplot of Points Averaged by Winery (Top 50)",
       x = "Winery",
       y = "Average Points") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("Visualizations/avg_points_by_top50_winery.png", top_50_wineries_points_graph, width = 8, height = 6, units = "in", dpi = 300)

top_50_wineries_points_graph
```

```{r}
# scatterplot of wineries by average price
winery_counts = wine_reviews %>%
  group_by(winery) %>%
  summarise(observations = n())

top_50_wineries = winery_counts %>%
  top_n(50, wt = observations) %>%
  pull(winery)

top_50_wineries = wine_reviews %>%
  filter(winery %in% top_50_wineries)

top_50_wineries_price_graph = ggplot(top_50_wineries, aes(x = winery, y = price, color = country)) +
  stat_summary(fun = "mean", geom = "point", size = 3) +
  labs(title = "Scatterplot of Price Averaged by Winery (Top 50)",
       x = "Winery",
       y = "Average Price") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("Visualizations/avg_price_by_top50_winery.png", top_50_wineries_price_graph, width = 8, height = 6, units = "in", dpi = 300)

top_50_wineries_price_graph
```

```{r}
# scatterplot of varieties by average points
variety_counts = wine_reviews %>%
  group_by(variety) %>%
  summarise(observations = n())

top_50_varieties = variety_counts %>%
  top_n(50, wt = observations) %>%
  pull(variety)

top_50_varieties = wine_reviews %>%
  filter(variety %in% top_50_varieties)

top_50_varieties_points_graph = ggplot(top_50_varieties, aes(x = variety, y = points, color = price)) +
  stat_summary(fun = "mean", geom = "point", size = 3) +
  labs(title = "Scatterplot of Points Averaged by Variety (Top 50)",
       x = "Variety",
       y = "Average Points") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("Visualizations/avg_points_by_top50_variety.png", top_50_varieties_points_graph, width = 8, height = 6, units = "in", dpi = 300)

top_50_varieties_points_graph
```

```{r}
# scatterplot of varieties by average price
variety_counts = wine_reviews %>%
  group_by(variety) %>%
  summarise(observations = n())

top_50_varieties = variety_counts %>%
  top_n(50, wt = observations) %>%
  pull(variety)

top_50_varieties = wine_reviews %>%
  filter(variety %in% top_50_varieties)

top_50_varieties_price_graph = ggplot(top_50_varieties, aes(x = variety, y = price, color = points)) +
  stat_summary(fun = "mean", geom = "point", size = 3) +
  labs(title = "Scatterplot of Price Averaged by Variety (Top 50)",
       x = "Variety",
       y = "Average Price") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("Visualizations/avg_price_by_top50_variety.png", top_50_varieties_price_graph, width = 8, height = 6, units = "in", dpi = 300)

top_50_varieties_price_graph
```


```{r}
# Points by price grouped by country
country_data <- wine_reviews %>%
  group_by(country) %>%
  summarise(avg_price = mean(price, na.rm = TRUE),
            avg_points = mean(points, na.rm = TRUE))

points_by_price_country <- ggplot(country_data, aes(x = avg_price, y = avg_points, color = country, label = country)) +
  geom_point() +
  geom_text_repel(
    box.padding = 0.5,
    point.padding = 0.1,
    force = 5,
    max.overlaps = Inf,
    size = 2
  ) +
  geom_smooth(aes(group = 1), method = "lm", se = FALSE, alpha = 0.1) +
  labs(title = "Average Wine Reviews by Country", x = "Average Price", y = "Average Points") +
  theme_minimal() +
  guides(color = FALSE) +
  theme(plot.margin = margin(1, 0.1, 1, 1, "cm"))

ggsave("Visualizations/groupby_country_points_vs_price.png", points_by_price_country, width = 8, height = 6, units = "in", dpi = 300)

country_data
points_by_price_country
```

